CREATE TABLE CLIENTE(
  ID_CLIENTE   INT PRIMARY KEY NOT NULL,
  NOMBRE       VARCHAR(30) NOT NULL,
  APELLIDO     VARCHAR(30) NOT NULL,
  DNI          VARCHAR(11) NOT NULL,
  DOMICILIO    VARCHAR(60) NOT NULL,
  ID_COMPROBANTE  VARCHAR(60) NOT NULL
);
CREATE TABLE COMPROBANTE(
  ID_COMPROBANTE   INT PRIMARY KEY NOT NULL,
  FECHA		   VARCHAR(10) NOT NULL,
  TOTAL		   FLOAT NOT NULL,
  ID_CLIENTE       INT NOT NULL
  FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);
CREATE TABLE ITEM(
  ID_ITEM      INT PRIMARY KEY NOT NULL,
  CANTIDAD     INT NOT NULL,
  DESCRIPCION  VARCHAR(30) NOT NULL,
  PRECIO       FLOAT NOT NULL,
);
INSERT INTO CLIENTE VALUES (1, 'Inna', 'Chorna', 12345678, 'Av.Cabildo 210',1);
INSERT INTO COMPROBANTE VALUES (1, '2023-07-25', 1500, 1);
INSERT INTO COMPROBANTE VALUES (2, '2023-07-25', 3200, 1);
INSERT INTO ITEM VALUES (1, 200, 'Celular Motorola G3', 78000);
